[package]
name = "rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1" , features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.63"